// AI 工具数据
const toolsData = [
    {
        id: 1,
        name: "ChatGPT",
        icon: "💬",
        category: "writing",
        categoryName: "写作助手",
        description: "OpenAI 推出的对话式 AI，可以进行写作、问答、翻译、编程辅助等多种任务。",
        tags: ["对话", "写作", "编程", "分析"],
        price: "免费 / Pro $20/月",
        url: "https://chat.openai.com"
    },
    {
        id: 2,
        name: "Claude",
        icon: "🧠",
        category: "writing",
        categoryName: "写作助手",
        description: "Anthropic 开发的 AI 助手，以长文档处理和安全性著称，适合写作和分析。",
        tags: ["对话", "写作", "分析", "研究"],
        price: "免费 / Pro $20/月",
        url: "https://claude.ai"
    },
    {
        id: 3,
        name: "Midjourney",
        icon: "🎨",
        category: "image",
        categoryName: "图像生成",
        description: "最强的 AI 图像生成工具之一，通过文字描述生成高质量艺术作品。",
        tags: ["艺术", "设计", "插画"],
        price: "$10/月起",
        url: "https://midjourney.com"
    },
    {
        id: 4,
        name: "DALL-E 3",
        icon: "🖼️",
        category: "image",
        categoryName: "图像生成",
        description: "OpenAI 的图像生成模型，可以从文字描述创建逼真或创意图像。",
        tags: ["图像", "设计", "创意"],
        price: "按次付费",
        url: "https://openai.com/dall-e-3"
    },
    {
        id: 5,
        name: "Stable Diffusion",
        icon: "⚡",
        category: "image",
        categoryName: "图像生成",
        description: "开源的 AI 图像生成模型，可以本地部署，完全免费使用。",
        tags: ["开源", "免费", "本地部署"],
        price: "免费",
        url: "https://stability.ai"
    },
    {
        id: 6,
        name: "Runway",
        icon: "🎬",
        category: "video",
        categoryName: "视频生成",
        description: "AI 视频编辑和生成工具，支持视频扩展、物体移除、风格转换等。",
        tags: ["视频编辑", "AI生成", "特效"],
        price: "免费 / Pro $35/月",
        url: "https://runwayml.com"
    },
    {
        id: 7,
        name: "HeyGen",
        icon: "👤",
        category: "video",
        categoryName: "视频生成",
        description: "AI 数字人视频生成工具，快速创建真人播报风格的视频。",
        tags: ["数字人", "播报", "营销"],
        price: "$29/月起",
        url: "https://heygen.com"
    },
    {
        id: 8,
        name: "Pika Labs",
        icon: "🎥",
        category: "video",
        categoryName: "视频生成",
        description: "新兴的 AI 视频生成平台，可以通过文字或图片生成短视频。",
        tags: ["视频生成", "AI", "创意"],
        price: "免费 / Pro $35/月",
        url: "https://pika.art"
    },
    {
        id: 9,
        name: "GitHub Copilot",
        icon: "💻",
        category: "code",
        categoryName: "编程助手",
        description: "AI 代码助手，与 VS Code 等 IDE 集成，提供实时代码建议。",
        tags: ["编程", "代码生成", "IDE插件"],
        price: "$10/月",
        url: "https://github.com/features/copilot"
    },
    {
        id: 10,
        name: "Cursor",
        icon: "🖱️",
        category: "code",
        categoryName: "编程助手",
        description: "AI 优先的代码编辑器，基于 VS Code，支持整文件编辑和智能重构。",
        tags: ["编辑器", "编程", "AI"],
        price: "免费 / Pro $20/月",
        url: "https://cursor.sh"
    },
    {
        id: 11,
        name: "v0",
        icon: "🧩",
        category: "code",
        categoryName: "编程助手",
        description: "Vercel 推出的 AI UI 生成器，通过文字描述生成 React 组件代码。",
        tags: ["UI", "React", "前端"],
        price: "免费 / Pro $25/月",
        url: "https://v0.dev"
    },
    {
        id: 12,
        name: "Notion AI",
        icon: "📝",
        category: "productivity",
        categoryName: "效率工具",
        description: "Notion 内置的 AI 助手，帮助写作、总结、翻译和头脑风暴。",
        tags: ["笔记", "写作", "协作"],
        price: "$10/月",
        url: "https://notion.so/product/ai"
    },
    {
        id: 13,
        name: "Perplexity",
        icon: "🔍",
        category: "productivity",
        categoryName: "效率工具",
        description: "AI 搜索引擎，可以理解问题并提供带有来源的答案。",
        tags: ["搜索", "研究", "问答"],
        price: "免费 / Pro $20/月",
        url: "https://perplexity.ai"
    },
    {
        id: 14,
        name: "Gamma",
        icon: "📊",
        category: "productivity",
        categoryName: "效率工具",
        description: "AI PPT 生成工具，通过大纲自动生成专业演示文稿。",
        tags: ["PPT", "演示", "设计"],
        price: "免费 / Pro $15/月",
        url: "https://gamma.app"
    },
    {
        id: 15,
        name: "ElevenLabs",
        icon: "🎤",
        category: "audio",
        categoryName: "音频生成",
        description: "AI 语音合成工具，生成自然逼真的语音，支持多语言。",
        tags: ["语音合成", "配音", "TTS"],
        price: "免费 / Pro $11/月",
        url: "https://elevenlabs.io"
    },
    {
        id: 16,
        name: "Mubert",
        icon: "🎵",
        category: "audio",
        categoryName: "音频生成",
        description: "AI 音乐生成平台，可以快速生成免版权的背景音乐。",
        tags: ["音乐", "背景音", "免版权"],
        price: "免费 / Pro $19/月",
        url: "https://mubert.com"
    },
    {
        id: 17,
        name: "Suno",
        icon: "🎶",
        category: "audio",
        categoryName: "音频生成",
        description: "AI 音乐生成器，可以用文字描述创作完整的歌曲。",
        tags: ["音乐创作", "AI", "歌曲"],
        price: "免费 / Pro $10/月",
        url: "https://suno.ai"
    },
    {
        id: 18,
        name: "Jasper",
        icon: "✍️",
        category: "writing",
        categoryName: "写作助手",
        description: "企业级 AI 写作工具，专为营销内容设计，支持多模板。",
        tags: ["营销", "文案", "SEO"],
        price: "$49/月起",
        url: "https://jasper.ai"
    },
    {
        id: 19,
        name: "Canva AI",
        icon: "🎯",
        category: "image",
        categoryName: "图像生成",
        description: "Canva 内置的 AI 工具，包括图像生成、背景移除、智能设计建议。",
        tags: ["设计", "海报", "社交媒体"],
        price: "免费 / Pro $13/月",
        url: "https://canva.com"
    },
    {
        id: 20,
        name: "Adobe Firefly",
        icon: "🔥",
        category: "image",
        categoryName: "图像生成",
        description: "Adobe 的 AI 创意工具，集成在 Photoshop 等产品中。",
        tags: ["设计", "PS", "创意"],
        price: "免费 / Pro $22.99/月",
        url: "https://adobe.com/firefly"
    },
    {
        id: 21,
        name: "Copy.ai",
        icon: "📋",
        category: "writing",
        categoryName: "写作助手",
        description: "AI 文案生成工具，提供 90+ 种模板，快速生成营销文案。",
        tags: ["文案", "营销", "模板"],
        price: "免费 / Pro $49/月",
        url: "https://copy.ai"
    },
    {
        id: 22,
        name: "Beautiful.ai",
        icon: "📈",
        category: "productivity",
        categoryName: "效率工具",
        description: "AI PPT 生成工具，自动美化幻灯片，让演示更专业。",
        tags: ["PPT", "演示", "自动化"],
        price: "$12/月起",
        url: "https://beautiful.ai"
    },
    {
        id: 23,
        name: "Whisper",
        icon: "🎧",
        category: "audio",
        categoryName: "音频生成",
        description: "OpenAI 的语音识别模型，支持 98 种语言的转录。",
        tags: ["转录", "语音识别", "免费"],
        price: "免费",
        url: "https://openai.com/research/whisper"
    },
    {
        id: 24,
        name: "Devin",
        icon: "🤖",
        category: "code",
        categoryName: "编程助手",
        description: "Cognition AI 推出的全球首个 AI 软件工程师，能独立完成编程任务。",
        tags: ["AI工程师", "编程", "自动化"],
        price: "$500/月",
        url: "https://cognition.ai"
    },
    {
        id: 25,
        name: "Kimi",
        icon: "🌙",
        category: "writing",
        categoryName: "写作助手",
        description: "月之暗面推出的中文 AI，支持长文本处理，200 万字上下文。",
        tags: ["中文", "长文本", "分析"],
        price: "免费",
        url: "https://kimi.ai"
    },
    {
        id: 26,
        name: "通义千问",
        icon: "🔮",
        category: "writing",
        categoryName: "写作助手",
        description: "阿里推出的中文大语言模型，支持多轮对话和文档分析。",
        tags: ["中文", "对话", "企业"],
        price: "免费",
        url: "https://tongyi.aliyun.com"
    },
    {
        id: 27,
        name: "讯飞星火",
        icon: "⭐",
        category: "writing",
        categoryName: "写作助手",
        description: "讯飞推出的认知大模型，支持多模态交互和行业应用。",
        tags: ["中文", "语音", "多模态"],
        price: "免费",
        url: "https://xinghuo.xfyun.cn"
    },
    {
        id: 28,
        name: "文心一言",
        icon: "📖",
        category: "writing",
        categoryName: "写作助手",
        description: "百度推出的知识增强大语言模型，中文理解能力强。",
        tags: ["中文", "知识增强", "搜索"],
        price: "免费 / Pro $49.9/月",
        url: "https://yiyan.baidu.com"
    }
];
